# TravisCI configuration for szepeviktor/unique-email-address

language: "php"
os:
  - "linux"
dist: "bionic"

php:
  - "8.1"
  - "8.0"
  - "7.4"

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  - "phpenv config-rm xdebug.ini"

install:
  - "composer update --no-interaction"

script:
  - "composer exec -- pest"
  - "composer exec -- phpstan"
