# TravisCI configuration for szepeviktor/unique-email-address

language: "php"
os:
  - "linux"
dist: "bionic"

php:
  - "7.4"
  - "7.3"

job:
  include:
    - php: "nightly"
      install: "composer update --no-interaction --ignore-platform-reqs"

cache:
  directories:
    - "${HOME}/.composer/cache"

install:
  - "composer update --no-interaction"

script:
  - "vendor/bin/pest"
  - "vendor/bin/phpstan analyze"
