# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Public Suffix List"

on:  # yamllint disable-line rule:truthy
    schedule:
    # Update Monday
    - cron: "30 04 * * 1"
    workflow_dispatch: null
    pull_request: null

permissions:
    contents: "write"
    pull-requests: "write"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    update:
        name: "Update"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Update list"
            run: |
                echo "$(lsb_release --short --id)-$(lsb_release --short --release)"
                echo OK:
